version: '2.0'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: resourcemap
      MYSQL_PASSWORD: resourcemap
      MYSQL_DATABASE: resourcemap
    volumes:
      - db:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:1.7
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - elastic:/usr/share/elasticsearch/data

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis:/data

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      ELASTICSEARCH_URL: 'elasticsearch:9200'
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: 'mysql2://resourcemap:resourcemap@db:3306/resourcemap'
      SETTINGS__HOST: 'localhost:4000'
      NGINX_PORT: 4000
    env_file: ./docker-env
    pid: host
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - db
      - elasticsearch
      - redis
    ports:
      - 4000:4000

  resque:
    <<: *rails
    command: rake resque:work TERM_CHILD=1 FORK_PER_JOB=false
    ports: []

  resque_scheduler:
    <<: *rails
    command: rake resque:scheduler
    ports: []

volumes:
  db:
  elastic:
  redis:
  uploads:
