version: '2.0'

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      RAILS_ENV:
      ELASTICSEARCH_URL: 'elasticsearch:9200'
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: 'mysql2://root@db'
      DATABASE_HOST: db
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
