version: '2.0'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: resourcemap
      MYSQL_PASSWORD: resourcemap
      MYSQL_DATABASE: resourcemap
    volumes:
      - db:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:1.7
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - elastic:/usr/share/elasticsearch/data

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis:/data

  smtp:
    image: 'djfarrelly/maildev:latest'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'

  web: &app
    image: instedd/resourcemap:latest
    environment:
      RAILS_ENV: production
      ELASTICSEARCH_URL: 'elasticsearch:9200'
      REDIS_URL: 'redis://redis:6379'
      DATABASE_URL: 'mysql2://resourcemap:resourcemap@db:3306/resourcemap'
      SETTINGS__HOST: 'localhost:4000'
      NGINX_PORT: 4000
      SETTINGS__SMTP__ADDRESS: smtp
      SETTINGS__SMTP__PASSWORD: smtp
      SETTINGS__SMTP__PORT: 1025
      SETTINGS__SMTP__USER_NAME: smtp
    env_file: ./docker-env
    pid: host
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - db
      - elasticsearch
      - redis
      - smtp
    ports:
      - 4000:4000

  resque:
    <<: *app
    command: rake resque:work TERM_CHILD=1 FORK_PER_JOB=false
    ports: []

  resque_scheduler:
    <<: *app
    command: rake resque:scheduler
    ports: []

volumes:
  db:
  elastic:
  redis:
  uploads:
