version: '2.0'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:1.7
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - elastic:/usr/share/elasticsearch/data

  redis:
    image: redis

  web:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: bundle exec rails server -b 0.0.0.0
    links: &links
      - db
      - elasticsearch
      - redis
    ports:
      - 3000:3000

  resque:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: bundle exec rake resque:work TERM_CHILD=1 FORK_PER_JOB=false
    links: *links

  resque_scheduler:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: bundle exec rake resque:scheduler
    links: *links

volumes:
  db:
  elastic:
  redis:
  bundle:
