version: '2.0'

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:1.7
    command: elasticsearch -Des.network.host=0.0.0.0
    volumes:
      - elastic:/usr/share/elasticsearch/data

  redis:
    image: redis:4.0-alpine
    volumes:
      - redis:/data

  smtp:
    image: 'djfarrelly/maildev:latest'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      RAILS_ENV:
      ELASTICSEARCH_URL: 'elasticsearch:9200'
      REDIS_URL: 'redis://redis:6379'
      DATABASE_HOST: 'db'
      SELENIUM_URL: 'http://selenium:4444/'
      SETTINGS__SMTP__ADDRESS: smtp
      SETTINGS__SMTP__PASSWORD: smtp
      SETTINGS__SMTP__PORT: 1025
      SETTINGS__SMTP__USER_NAME: smtp
    pid: host
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - elasticsearch
      - redis
      - smtp
      - selenium
      - resque
      - resque_scheduler
    command: rails server -b 0.0.0.0
    ports:
      - 3000:3000

  selenium:
    image: selenium/standalone-firefox:3.11
    shm_size: 2g
    volumes:
      - .:/app

  resque:
    <<: *rails
    command: rake resque:work TERM_CHILD=1 FORK_PER_JOB=false
    ports: []
    depends_on: []

  resque_scheduler:
    <<: *rails
    command: rake resque:scheduler
    ports: []
    depends_on: []

  jasmine:
    <<: *rails
    command: rake jasmine
    ports:
      - 8888:8888
    depends_on: []

volumes:
  db:
  elastic:
  redis:
  bundle:
