production:
  url: http://nuntium.instedd.org
  account:
  application:
  password:

development:
  url: http://nuntium.instedd.org
  account:
  application:
  password:

testing:
  url: http://nuntium.instedd.org
  account:
  application:
  password:
