mobile_id: off
host: localhost:3000

plugins:
  public_collection: on
  snapshot: on
  channels: off
  reminders: on
  alerts: on
  fred_api: on
  csd_api: on

# smtp:
#   host: 'localhost'
#   domain: 'localhost'
#   port: 25
#   username:
#   password:
#   authentication: 'plain'

# google_maps_key: changeme
