#!/usr/bin/env ruby

puts "Loading Rails..."
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)

sites = Site.includes(:collection)
count = sites.count

i = 0.0
sites.find_each do |site|
  i += 1
  percentage = (100 * (i / count)).round
  print "\rMigrating site #{i.to_i}/#{count}: %#{percentage}"

  fields = site.collection.fields.index_by(&:code)

  if site.properties.present?
    props = {}
    site.properties.each do |key, value|
      field = fields[key]
      if field
        props[field.es_code] = value
      else
        props[key] = value
      end
    end
    site.properties = props
  end

  site.mute_activities = true
  site.save!
end

puts "\rMigrating sites: %100"
