#!/usr/bin/env ruby

puts "Loading Rails..."
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)

collections = Collection
count = collections.count

i = 0.0
collections.find_each do |collection|
  i += 1
  percentage = (100 * (i / count)).round
  print "\rRecreating collection #{i.to_i}/#{count}: %#{percentage}"
  collection.recreate_index
end

print "\r#{' ' * 80}"
print "\rDone!"
