#!/usr/bin/env ruby

puts "Loading Rails..."
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)

sites = Site.where(:group => :false)
count = sites.count
current = 0

i = 0.0
sites.find_each do |site|
  i += 1
  percentage = (100 * (i / count)).round
  print "\rIndexing sites: %#{percentage}"
  site.store_in_index
end

puts "\rIndexing sites: %100"
