#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require File.expand_path('../../config/environment',  __FILE__)

Elasticsearch::Client.new.indices.delete index: "_all"

[Collection, Site, Layer, Field, Membership].each &:delete_all
