name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set environment up
        run: |
          mv docker-compose.ci.yml docker-compose.override.yml
          docker-compose pull
          docker-compose up -d db elasticsearch redis
          docker-compose run --rm --no-deps web bundle
          docker-compose run --rm --no-deps web rake db:setup
          docker-compose run --rm --no-deps web rake db:test:prepare

      - name: Run specs
        run: |
          docker-compose run --rm web bundle exec rspec spec/ plugins/
          # docker-compose run --rm web bundle exec rspec -t js spec/integration/
          # docker-compose run --rm web bundle exec rake jasmine:ci

  build:
    needs: test
    runs-on: ubuntu-20.04
    env:
      DOCKER_REPOSITORY: 'instedd/resourcemap'
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v2
      - name: Build image & push to Docker Hub
        run: ./build.sh
